### ISSUE TITLE
Nothing under 'Musical Interests'

### ISSUE THREAD

**Issue by ddaygold** [Flamacue/personal_website#1]
Bug in music.html

There isn't anything listed under 'Musical Interests' . From personal experience, I know this isn't true. For logs pertaining to this bug, see below:

![image](https://cloud.githubusercontent.com/assets/2137679/7946708/c20e3bb2-093d-11e5-81cf-5c17b96d7126.png)

**Comment by Flamacue** [comment]
Thanks, our team is working as hard as we can to get it fixed!
